const Ability = Object.freeze({
    None: 0,
    Fetch: 1,
    Boot: 2,
    Peek: 3,
    Full: 4,
    Combo: 5,
    Guest: 6,
    Trouble: 7,
    ReduceTrouble: 8,
    CancelTrouble: 9,
});

const animals = {
    "cow": {
        id: "cow",
        name: "Cow",
        canBuy: false,
        cost: 0,
        cuteness: 2,
        cash: 0,
        ability: Ability.Trouble,
        stars: 0,
    },
    "hamster": {
        id: "hamster",
        name: "Hamster",
        canBuy: true,
        cost: 2,
        cuteness: 1,
        cash: 0,
        ability: Ability.None,
        stars: 0,
    },
    "fish": {
        id: "fish",
        name: "Fishy",
        canBuy: true,
        cost: 3,
        cuteness: 0,
        cash: 1,
        ability: Ability.None,
        stars: 0,
    },
    "golden": {
        id: "golden",
        name: "Golden Retriever",
        canBuy: true,
        cost: 3,
        cuteness: 0,
        cash: 0,
        ability: Ability.Fetch,
        stars: 0,
    },
    "snake": {
        id: "snake",
        name: "Snake",
        canBuy: true,
        cost: 3,
        cuteness: 4,
        cash: 0,
        ability: Ability.Trouble,
        stars: 0,
    },
    "horse": {
        id: "horse",
        name: "Horse",
        canBuy: true,
        cost: 4,
        cuteness: 0,
        cash: 0,
        ability: Ability.Boot,
        stars: 0,
    },
    "pig": {
        id: "pig",
        name: "Pig",
        canBuy: true,
        cost: 4,
        cuteness: -1,
        cash: 2,
        ability: Ability.None,
        stars: 0,
    },
    "black_cat": {
        id: "black_cat",
        name: "Black Cat",
        canBuy: true,
        cost: 4,
        cuteness: 2,
        cash: 0,
        ability: Ability.Peek,
        stars: 0,
    },
    "turtle": {
        id: "turtle",
        name: "Turtle",
        canBuy: true,
        cost: 4,
        cuteness: 1,
        cash: 0,
        ability: Ability.ReduceTrouble,
        stars: 0,
    },
    "parrot": {
        id: "parrot",
        name: "Parrot",
        canBuy: true,
        cost: 5,
        cuteness: 3,
        cash: 2,
        ability: Ability.Trouble,
        stars: 0,
    },
    "mouse": {
        id: "mouse",
        name: "Mouse",
        canBuy: true,
        cost: 5,
        cuteness: 0,
        cash: -1,
        ability: Ability.Full,
        stars: 0,
    },
    "rabbit": {
        id: "rabbit",
        name: "Rabbit",
        canBuy: true,
        cost: 5,
        cuteness: 4,
        cash: -1,
        ability: Ability.None,
        stars: 0,
    },
    "sheep": {
        id: "sheep",
        name: "Sheep",
        canBuy: true,
        cost: 5,
        cuteness: 3,
        cash: 0,
        ability: Ability.Guest,
        stars: 0,
    },
    "bee": {
        id: "bee",
        name: "Honey Bee",
        canBuy: true,
        cost: 7,
        cuteness: 0,
        cash: 0,
        ability: Ability.Combo,
        stars: 0,
    },
    "chicken": {
        id: "chicken",
        name: "Chicken",
        canBuy: true,
        cost: 9,
        cuteness: 0,
        cash: 3,
        ability: Ability.None,
        stars: 0,
    },
    "alpaca": {
        id: "alpaca",
        name: "Alpaca",
        canBuy: true,
        cost: 40,
        cuteness: 0,
        cash: 0,
        ability: Ability.None,
        stars: 1,
    },
};

const packs = {
    "standard": ["cow", "hamster", "fish", "golden", "snake", "horse", "pig", "black_cat", "turtle", "parrot", "mouse", "rabbit", "sheep", "bee", "chicken", "alpaca"]
};
